# Datasource — SQL Server (local ou Docker na porta 1433)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bd_renovar_dev;encrypt=false;trustServerCertificate=true
spring.datasource.username=${MSSQL_USERNAME}
spring.datasource.password=${SA_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.web=INFO

# RabbitMQ (local ou Docker na porta 5672)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASS}
